# Nombre de la aplicación (Identificador en el clúster)
spring.application.name=microservicio-devops

# ==========================================
# OBSERVABILIDAD Y MÉTRICAS (IE1 y IE3)
# ==========================================
# Expone los endpoints de salud, info y el formato nativo de Prometheus
management.endpoints.web.exposure.include=health,info,prometheus

# Habilita métricas detalladas de las solicitudes HTTP del microservicio
management.metrics.web.server.request.autotime.enabled=true

# ==========================================
# CONFIGURACIÓN DE LOGS (IE1)
# ==========================================
# Define el nivel de log por defecto para capturar errores y advertencias
logging.level.root=INFO
logging.level.cl.duoc.microserviciodevops=DEBUG

# Formato estructurado de logs en consola (útil para que herramientas de nube los procesen)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n